project:
  type: website

website:
  title: "Website_Quarto1"
  navbar:
    left:
      - href: my-quarto-site.qmd
        text: Home
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

extensions:
  - mermaid

